name: CI

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Check gfortran compiler
        run: |
          gfortran --version

      - name: Compile src code for testing
        run: |
          gfortran -o fluor src/test_fluorescence_corsika.F

      - name: Run test
        run: |
          ./fluor

      - run: echo "Job's status ${{ job.status }}."
